# Generated by Django 5.1.7 on 2025-04-11 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investie', '0002_alter_watchlist_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='user',
            new_name='user_id',
        ),
    ]
