# Generated by Django 5.1.7 on 2025-04-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investie', '0003_rename_user_watchlist_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='user_id',
            field=models.CharField(max_length=255),
        ),
    ]
