# Generated by Django 5.1.7 on 2025-04-11 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investie', '0004_alter_watchlist_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='user_id',
            new_name='user',
        ),
    ]
